label chapter2:
    scene black
    with slowDissolve
    
    show text chapterText(2, "The Training") with dissolve
    pause
    scene black with dissolve
    show text bookText("The candle of God is the soul of Man, searching the chambers of the depths.", "Proverbs 20:27") with dissolve
    pause
    scene black with dissolve   
    
    "A few years have passed since Pinny and I made rope hammocks in the park trees."
    "We're still friends, but the world around us has... changed... a lot."
    "Zusha's {i}cheder{/i} group was never that large, and when all the kids got older, the community hired another teacher for us, replacing him."
    "So, Zusha moved away. To Oklahoma City, I think."
    "We hardly heard from him again."
    "I miss him a lot, and I'm sure Pinny does, too."
    "But that wasn't all."
    "When the recession hit, my dad lost his office job."
    "Without that income, my parents could no longer afford the tuition for a Jewish education."
    "So, when I was ten, I went into public school."
    "I didn't want to."
    "Pinny and Yossi and my other friends were still in the Jewish school."
    "Going to the new school was a big shock."
    "Everyone was talking about what was \"in.\""
    "Being \"in\" was a concept that I had never seen or heard of before."
    "It seemed that to be \"in,\" you had to know the latest rap song and be able to break dance and play sports."
    "The values just seemed so hollow."
    "I didn't want to become like that."

    inner  "So, nu?"
    inner "What do you want to be?"
    "What I was, what I wanted to be... it bothered me at night, too."
    "Why couldn't things be simple, like they were before?"
    
    zu_mem "Your mission, though. Hmmm-hm."
    zu_mem "Well, what would you like to do?"
    me_mem "I wanna be tsadik just like little Yisroël!"

    "Oh, how much has changed since then!"
    "The loneliness, the darkness around me now didn't exist back then."
    "Now, it seems to cast a shadow over everything."
    "Even physically, the grass and the sky don't seem to shine as brightly as in my memories."
    shout "{i}Do you still even want to be a tsadik?{/i}"
    me "..."
    me "Yes... I think."
    me "Well, I {i}want to{/i} want to be one..."
    me "But..."
    me "I don't know."
    me "I guess..."
    inner "...Other things have pushed it aside."
    me "Well, yes. I guess they have."
    me "I really like building gadgets in the workshop downstairs. Making music. Writing."
    inner "You can't choose all of them, you know. Only one."
    inner "Only if you focus your efforts can you actually {i}do.{/i}"
    me "Do what?"
    inner "Well, what do {i}you{/i} want to do?"
    me "..."
    me "I do like helping others..."
    me "I guess a little spark of my old desire is still there."
    me "To be a tsadik."
    "I look more closely at it."
    inner "A worthy choice."
    inner "But you are still full of doubt."
    inner "You genuinely like the other things too, don't you?"
    me "..."
    me "Yes, I do."
    inner "Like music."
    me "Yes, but..."
    me "...if I go after these other interests, could my work actually impact anyone?"
    me "Music might inpire someone for a moment, but once the music passes, the inspiration is gone, too."
    me "Music alone can't change a person's whole life."
    me "Not unless it becomes his job, and his whole life revolves around it."
    me "Even then, does he become a better person?"
    inner "Okay, so you won't devote your life to music. I can understand that."
    inner "What about making gadgets?"
    inner "That will definitely have an impact. Just look at the past ten years!"
    "He's right."
    "Web 2.0. The iPhone. Smartcards. Video chat. Facebook."
    "But..."
    "...the answer has no soul. Somehow."
    me "Well, you're right. Technology can change our lives."
    me "It can even change the world. It has."
    me "But its power and flexibility is also its weakness."
    me "Technology is just another kind of power. It's a body with no soul."
    me "Just like money, energy, intelligence."
    me "It is neither good nor evil by itself."
    me "It all depends on the one who uses it."
    me "But there is no way I can make sure it is used for good."
    me "Besides, even if I did develop something that could, say, stop all war, how long would that last before another, more powerful technology comes along?"
    me "Technology is constantly changing."
    me "My invention could even be used in a weapon!"
    me "After all, destroying is easier than building."
    me "I've seen that in my workshop downstairs."
    inner "Touché."
    "I pause and think some more."
    me "What else could I do?"
    inner "Well, if you are worried about making sure it helps and does good, what about writing?"
    inner "Writing can be inspire people. It could even be useful."
    me "That's true."
    me "But only as long as they remember what I write about."
    me "If I write about something, the only people who will constantly remember it are those whose lives revolve around it."
    me "I think that would rule out fiction. People's lives can't revolve around that."
    inner "Ah, but can't it have an impact? Isn't it inspiring?"
    me "Yeah, that's true."
    me "But ultimately, fiction doesn't really exist."
    inner "What do you mean? Don't these universes exist in people's hearts?"
    inner "Like Tolkien's Lord of the Rings."
    inner "Everyone says it's a masterpiece. Tolkien devoted nearly his entire life to it."
    inner "The story has so much depth. So much that rings true!"
    inner "Epic quests. The war between Good and Evil. A world of lords, heroes and kings."
    inner "You can't tell me that's not inspiring."
    "At first, I can't answer. He has a point, but something is wrong."
    me "...Well, I've got to agree on that, at least. It's inspiring."
    me "Heck, the sheer depth, quality, detail and passion of the series is impressive. It's awesome."
    me "Noble warriors, legends of courage, tales of eternal love. Yes."
    me "Truly, an epic story. Magnificent. Inspirational." 
    "Then it hit me. What was wrong with it."
    me "But do people really live differently because of it? Did it really change the world?"
    me "Aside from the film padding some wallets and depleting some others, did Tolkien have a tangible effect on the world?"
    me "I really want to say it did."
    me "An effort like that, a passion like that deserves it."
    me "But I can't see it."
    me "..."
    me "I think the tale was so magical and legendary that it remained trapped in Middle-Earth."
    inner "Hoooo."
    inner "Tricky, tricky, isn't it?"
    inner "For one thing, it's got to inspire other people."
    inner "{i}And{/i} it has to inspire in a good way."
    inner "And not only that, it's got to change the world in a down-to-earth way."
    me "So..."
    me "...I'll be a tsadik."
    inner "Hahahaha!"
    inner "You say that so easily."
    inner "You think that {i}you{/i} can be a tsadik?"
    me "I..."
    
    me "I don't know."
    inner "Exactly. Back to square one."
    inner "You still have so many doubts."
    inner "Do you want to devote your entire life to this?"
    inner "Is it even possible for you to achieve this?"
    inner "Isn't it too much to expect perfection from yourself?"
    inner "Can {i}anyone{/i} achieve this?"
    me "But they can! They have!"
    me "Zusha told me!"
    me "There's the Baal Shem Tov, Rabbi Akiva, Hillel, Moishe Rabeinu!"
    me "They all existed! they did it!"

    inner "Yes, but that's {i}them.{/i}"
    inner "What about you?"
    inner "They lived in an age of miracles."
    inner "Not you."
    inner "They were towers of morality and faith!"
    inner "Do you think you can measure up to them?"
    inner "Besides, their time was different from ours."
    inner "You, on the other hand..."
    inner "You are just a puny speck of dust next to them. In an age of darkness."
    inner "Just look around you."
    "I couldn't argue."
    "My throat began to catch."
    me "Why..."
    me "Why was I born into such an age?"
    me "When Godliness is hidden?"
    me "This is... too cruel..."
    inner "Yes, yes. But it's the truth."
    inner "Darkness surrounds you, all about!"
    inner "How do you think you can overcome this?"
    me "Please..."
    inner "Look at yourself honestly now. Can you even compare yourself to their level?"
    inner "In fact, you are already overcome!"
    "My eyelids tremble as my tears flow."
    "I know that I am nothing next to the spiritual giants of old."
    "But why does this bother me so much?"
    "Did I really expect myself to be perfect?"
    inner "Do you think that you are so holy?"
    me "No..."
    "My inner voice took on a more cynical air."
    inner "How many, how many?"
    inner "Just how many sins do you think have sullied your soul?"
    inner "A hundred? A thousand? Ten thousand?"
    me "NO!"
    inner "These sins here are only the ones you know about."
    inner "But God misses nothing."
    inner "He can count the ones you {i}don't{/i} know about, too!"
    me "Oy... Oy...."
    inner "Hopeless, no? Another here, another there..."
    me "AAAGH!!!"
    inner "And you want to be a tsadik?"
    inner "Ha!"
    inner "Ha! Ha! Hahahahaha!"
    me "NOOO!!!"
    "My darkened bedroom vibrates momentarily from my outburst."
    "I freeze in bed, frightened."
    "I think I woke my parents."
    "There is a pause. Then a rustling of sheets."
    "Down the hall, bare feet pad gently on the thin carpet. The floorboards creak slightly as the steps come closer."
    "It's my mom."
    mom "Benny?"
    "She switches on my desk lamp. It's not as bright as the overhead light, but it's enough to see my mom's worried face."
    mom "You were screaming."
    "I nod slightly."
    "She comes and sits on my bed, beside me."
    mom "Was it a nightmare?"
    me "..."
    me "Yeah."
    "I'm still shaking under the covers. I feel cold. My pajama top is sticky with sweat."
    mom "Do you want some water?"
    me "Yes, please."
    mom "Okay, Benny. I'll be right back."
    "A tinkle of glass tumblers. A faucet runs in the kitchen."
    "I notice how the pitch of the rushing water rises before the faucet shuts off."
    "Soon, she comes back in my room with a glass of water. Pushing away the sheets, I sit up and gratefully take it."
    me "Thanks, Mommy."
    "She smiles and sits next to me on the bed. She feels warm, reassuring."
    me "{i}Boruch atoh Adoinoi, Eloiheinu melech haöilom, shehakoil nihiyoh bidvaroi.{/i}"
    mom "{i}Omein.{/i}"
    "The water feels good on my dry throat. I put the glass down after a few gulps."
    "After sitting together like this for a while, my mom shifts a little."
    mom "Do you want to tell me about your nightmare?"
    "I pause a moment."
    me "It was about what I want to be when I grow up."
    "She nods."
    me "I don't really know. I think..."
    me "I think I want to be a tsadik."
    me "But I don't know if I can."
    me "It seems so hard to give up on everything else. The gadgets. The music."
    
    mom "Benny."
    mom "No matter what you become, I will always love you."
    mom "But please, Benny, don't give up on anything."
    mom "All the things you can do, God has given you as a gift."
    mom "Becoming a tsadik doesn't mean that you have to throw it all away."
    mom "The Rebbe said that we've got to use all of our skills, all of our power to bring Moshiach now."
    mom "A tsadik doesn't throw any of his talents away. He uses them to serve God."
    mom "Did you know that the Rebbe was an engineer?"
    me "No."
    mom "Before he became Rebbe, he did work for the US Navy."
    mom "Even after he became Rebbe, he would help other scientists with their work."
    me "I didn't know that."
    mom "Benny, you are special. God gave you special abilities."
    mom "Don't throw them away. Find a way to use them for good."
    "I nod."
    "We sit together a bit longer. I drink some more water."
    mom "Do you think you can sleep now?"
    me "Yeah, I think so."
    mom "I'll turn off the light, then."
    "She gets up and switches the lamp off again."
    mom "Good night, Benny. I love you!"
    me "Good night, Mommy."
    "She closes the door."
    me "I love you, too."

    "Her footsteps fade away in the renewed darkness, but I still feel her warmth."
    "I hug my knees to keep the warmth as long as I can."
    "After waiting a bit, I hear nothing."
    "Nothing but the crickets outside, and the fridge motor running, far off in the kitchen."
    "That, and the tiny, high-pitched noise of blood rushing in my ears."
    "That little noise never stops. It's never completely silent."
    "Just like my inner voice."
    "Always questioning."
    inner "Do you really want to be a tsadik?"
    "Doubting."
    inner "What do you want to be?"
    "Repeating."
    "I try to figure out what to do about it."
    "Should I ignore it?"
    "It might die down eventually."
    "If I manage to outlast it."
    shout "{i}What do you want to be?{/i}"
    "But is the question it asks really bad?"
    inner "What do you want to be?"
    "On the other hand, is that really what it's asking?"
    "I already answered the question. I want to be a tsadik!"
    "What is that inner voice really asking?"
    "Does it has a problem with the answer I'm giving?"
    inner "Exactly."
    inner "You answered in words. Did you answer with your core?"
    me "My core?"
    inner "I still heard doubt. Fear."
    me "Fear..."
    me "Yes, there is a fear there."
    me "A fear that I could fail."
    me "That I could be overcome."
    me "That I might never become a tsadik."
    me "A fear that I am hoping for too much."
    inner "You answered with words. Words are external."
    inner "Promises, promises. What will {i}actually{/i} happen?"
    me "What will {i}actually{/i} happen?"
    inner "Words can lie."
    shout "{i}But not your core.{/i}"
    inner "Look into your core. Your inner self. What do you want?"
    inner "What do you see?"
    me "Where {i}is{/i} my core?"
    inner "Until your inner self is sure, your future will contain fear and doubt."
    "I rest my head against my knees and whisper into the darkness."
    me "God... God... Where is my core?"
    "The outside world fades from my consciousness, leaving only me."
    "My body dissolves away just like it."
    me "God... Where is my core?"
    "My mind floats through the darkness."
    "I see random colors speckling my vision. An orange web, with rough, angular shapes of green."
    me "Please, God... where?"
    me "Where am {i}I?{/i}"
    me "What am I?"
    "My perception of time broadens."
    me "What was/will be me?"
    "The darkness deepens. I see something."
    "It has no recognizable form. It's just floating in nothingness."
    "It's dark. So dark!"
    "But there is a little light coming from it."
    "A tiny light."
    "Motionless."
    "I will it to change, but nothing happens."
    inner "You must decide with your core."
    "I strengthen my focus on it."
    "Still, nothing."
    inner "Decide... with your inner self."
    "Speckles fill my vision as I lose concentration."
    "A distant train horn sounds, and I hear the boxcars rattling over the tracks."
    "I open my eyes. I don't feel so tired."
    "I just feel lost. Something didn't click."
    "The alarm clock beside me glows 11:34 in red digits."
    "Despite my alertness, I get back under the covers and close my eyes."
    "I open then again. 11:34."
    "I close them for a while."
    "Then I open them. 11:36."
    "I shut them again."
    "11:39."
    "11:45."
    inner "Until your inner self is sure..."
    inner "...your future...."
    "The rest of the message is lost."
    "The voice disappears."
    "Then, it fades back in one last time."
    inner "What do you want to be?"
    "11:54."
    "I close my eyes again and focus on relaxing, not moving my body."
    "Sleep envelops me...."


    "The questions from last night still echo in my mind."
    me "Do I even know what a tsadik is?"
    me "I know what a tsadik does."
    me "But, if words are external, what about actions?"
    me "Compared to speech, aren't actions more external? Separated from the core?"
    me "But then, aren't they also an expression of the internal?"
    me "Aren't actions things that a person felt so necessary that he brought it from potential to actual?"
    me "What is the connection between speech and action?"
    "My thoughts wander aimlessly through the labyrinth."
    me "A tsadik doesn't lie."
    me "In a tsadik, his inside and outside match."
    me "His words and actions match his thoughts."
    inner "Yes. But..."
    inner "...it's much, much deeper than that."
    inner "Everything - his action, his speech, even his thoughts - everything is aligned with his inner self."
    inner "A tsadik's inner self is sure. Firm."
    inner "Since his externality flows from that, so does his future."
    inner "Everything comes because of his pure inner core."
    me "I guess that's the soul."
    me "But what about my question?"
    me "How do I become like that?"
    shout "{i}How do I strengthen my inner self?{/i}"
    me "How do I strengthen my soul?"
    me "How do I give it direction?"
    "... And so the day wears on. The questions cycle in my mind."


    "They are still circling in my mind when I meet Yossi."
    "Since Yossi lives nearby, we still see each other fairly often."
    scene bg forestPavedPath1 with dissolve
    me "Hmm? Oh! Hi Yossi!"
    ys "Benny!"
    "I smiled and greeted him, but my mind is still occupied."
    inner "Does strengthening the soul change what it is?"
    inner "Or does it just amplify what was there before?"
    me "I have no idea..."
    ys "Uh, Benny?"
    me "Is there something that can amplify it? Something I have to do?"
    ys "Oi, Benny."
    me "Or is it where I just plough ahead and do it?"
    ys "Hullo. Benny. Benny!"
    me "Huh?"
    ys "You've got that look again. What's up?"
    
    "I look at him."
    me "How do you become a tsadik?"
    ys "..."
    ys "*Hic?*"
    "Uh-oh. I got his hiccups started."
    ys "Ahhh-*hic*-*hic.*"
    me "Oh, no. Your hiccups-"
    ys "Gosh, Benny. *Hic.* You're so weird!"
    me "Sorry about that. I'm back now."
    ys "*Hic!*"
    me "But your hiccups-"
    ys "Don't wo- *hic* worry about it. *Hic.*"
    me "Breathe slowly."
    ys "*Hic.* That doesn't *hic* work."
    me "It doesn't?"
    ys "Do you *hic* have something *hic* to eat?"
    "... An ice cream later, he was back to normal."
    ys "Hah-h-h. Thanks, Benny."
    me "No problem!"
    "Of course, I didn't mind eating some ice cream either."
    me "{i}Boruch atoh adoinoi, eloiheinu melech haöilom, boirei nefashos rabois v'chesroinon al kol mo sheboroso lehachayois bohem nefesh kol chai...{/i}"
    ys "What're you saying?"
    me "{i}Boruch chei haöilomim.{/i} -For the ice cream pop."
    ys "You say a brocho after ice cream?"
    me "Yeah. I just noticed it in the bentsher last week, after the \"Grace After Meals.\""
    "A look of comprehension slowly dawns on him."
    ys "You mean, bentshing?"
    me "Yeah."
    ys "\"Grace After Meals.\" That sounds so Shakespeare!"
    me "Yeah, doesn't it?"
    ys "It's like \"Tabernacle\" for Mishkan and- em, what do they call the menorah?"
    me "Candelabrum. Isn't that so over-the-top?"
    ys "I know! Why can't they just use {i}normal English?{/i}"
    ys "\"Candelabrum\" - Oy vey!"
    "We both laugh together..."
    me "\"Tabernacle!\" Heehee!"
    ys "\"Mace After Greals!\" Haha!"
    "But then, I remember..."
    me "Wait, Yossi! Don't get the hiccups again!"
    ys "Hahaha! *Hic!*"
    me "{b}NO-O-O!{/b}"
    ys "Haha-*hic*-haha-*hic!*"
    me "You're so mean, Yossi!"
    ys "*Hic!* Hahahahaha!"
    me "I've got no money left! What're we gonna do now?"
    "But, Yossi is a good sport."
    "He bought the next round of ice creams."
    me "So what do you think about the question from before?"
    ys "Ummm... What was it?"
    me "The tsadik thing."
    ys "Oh, yeah. Hmmm...."
    ys "I guess...."
    ys "Emmm...."
    "He's speaking slowly, brow furrowed in thought."
    ys "You've gotta be a Talmud chochem. I think."
    "A chochem is a scholar."
    me "Talmud?"
    ys "Yeah. All those tsadikim in Zusha's stories were chochomim."
    ys "Maybe that's it."
    me "Hmmm."
    me "Oh! It's lunchtime!"
    "Yossi's mom was mostly strict about one thing, and that was mealtimes."
    ys "You're right! Gotta go!"
    me "See you later, Yossi!"
    ys "Bye!"
    "I feel kind of sorry for him."
    me "Two ice creams, then lunch..."
    "I cringe."
    me "Oooohhh. Poor guy!"
    me "..."
    me "Wait a minute..."
    me "What about me?"
    me "Ohhhh no. Oy vey."
    me "Oy vey, oy vey."
    
    scene black with mediumDissolve
    "That afternoon (after a {i}quick{/i} lunch), I took the one volume of Talmud Tatti had, and tried to read it in Aramaic."
    "It had the vowels added in, so sounding out the words wasn't too hard."
    me "{i}Sha... mm... mai? Om...er? Kol. Han...nashim?...{/i}"
    "It's just that I had absolutely no idea what I was reading at all."
    "But I kept reading."
    "For a while."
    "Then my eyelids began to droop."
    "And then I fell asleep on the couch."
    "I guess that I bit off more than I could chew."

    "Still, even though I didn't really get anything from that Talmud session on the couch..."
    "I'm glad I talked to Yossi."
    "He might not have answered my question, but I realized eventually that he introduced a new question, which I had a chance of answering."
    "The thing is, I have all these questions."
    "I haven't been finding the answers, because I've been looking them in the wrong places."
    "My new question, then, is..."
    shout "{i}Where can I find the answers?{/i}"
    "In other words, I'm alone. Others have come before me, seeking the same path."
    "Those people, the people who have already done this - they would know. They would know how to become a tsadik"
    "Chochomim. Tsadikim."
    "They would have the answers."
    "I've got to see what {i}they{/i} say."


    scene bg forestPathUp1 with dissolve
    "Spurred by this thought, I continued learning Torah on my own."
    "Especially the Oral Traditions, committed to writing by the chochomim and tsadikim of old."
    "At first, it was mostly stuff already translated into English."
    "I knew that it was filtered down a little bit, because the titles and authors clearly indicated their original language."
    "Pirkei Avos. Choivos Halevavos."
    "Rambam. Rabi Yochanan ben Zakai. Hillel."
    "While I did learn a fair deal, the English commentaries showed that there were thousands of nuances that could only be seen in the original language."
    "I wanted to see everything, as it was in the original."
    "When they say \"man,\" was the original word {i}adam? Ish? B'nei adam? Gever? Nefesh?{/i} They all have different shades of meaning!"
    "When they say \"glory,\" was the original {i}kavod,{/i} or was it {i}hod? Kavod{/i} can also mean \"honor,\" but {i}hod{/i} is related to {i}hodaä,{/i} which means \"acknowledgement\" and implies resolution of a conflict."
    "When I got older, I would put one finger in the Hebrew and one finger in the English at the same time. Matching up the words helped me learn the language."
    "It was slow going, but I made some progress."
    "When I was twelve, I could understand about half of the siddur, or the Jewish prayerbook."
    "At thirteen, I knew about 75\%, and I could understand about half of the Chumash, the Five Books of Moses."
    "It helped a lot that the vocabulary of the Holy Tongue was very simple, with few extra frills."
    "Or so I thought."
    "Later books of the Writings and the Prophets were much more flowery and poetic, and I couldn't even tell what the topic was most of the time."
    "Still though, I stuck with it."
    "Maybe it was because I found Pirkei Avos in the siddur one day after davening."
    "It was a huge collection of Jewish aphorisms - it really got into human psychology, self-improvement and stuff like that."
    "Or maybe it was because I kept asking questions from the rabbi and kept getting answers."
    "I started feeling that no matter what the question, there was always an answer."
    "Even if the initial answer was \"I don't know,\" I usually found the answer somewhere, sometime later on."
    "Maybe it was just that there were entire fields of Jewish knowledge that I had no idea about, like Talmud and Kabbalah."
    "The possibilities and knowledge just waiting out there made me want to go out and get it for myself."
    "But at the same time as I was exhilarated by the knowledge, I was also in awe and a bit of fear of it."
    "There is a story about this in the Talmud."
    scene black with mediumDissolve
    #Scene change here to indicate the beginning of a story
    "There are four levels of understanding Torah; four different realms."
    "There is P'shat, Remez, Drush and Sod. Each of these is true; there are 70 facets of meaning in the Torah, like gem that reveals new beauty at every angle."
    "P'shat is the plain meaning of the verse."
    "Remez is allusion, which links the verses in different places together."
    "Drush is more esoteric, explaining the finer hinting of the words in the Torah. Often, this contains the stories in between the lines of the Torah."
    "Sod is the deepest and most esoteric aspect of the Torah. Few people are privileged to learn it."
    "Sod means \"secret.\""
    "It covers the mystical aspects of Torah."
    "Together, these four layers of understanding are abbreviated as PaRDeS. The word Pardes itself means \"orchard.\""
    "Says the Talmud:"
    "\"There were four men that entered Pardes.\""
    "\"They were Ben Azai, Ben Zoma, Acher, and Rabbi Akiva.\""
    "\"He said to them:\""
    "\'When you reach the pure marble stones, do not say, \"Water, water!\"\'"
    "\'For it is said, \"One who speaks falsehood will not be guiltless in My eyes.\"\'"
    "\"Ben Azai peered in and died.\""
    "\"Scripture says of him, \'Precious in the eyes of God is the death of His pious.\'\""
    "\"Ben Zoma peered in and became insane.\""
    "\'Scripture says of him, \"Have you found honey? Eat what is enough for you, so that you not be filled with it and vomit it.\'\""
    "\"Acher cut down the plantings, [[going astray in heresy].\""
    "\"Rabbi Akiva came out in peace.\""
    #Scene change back to normal
    "This Aggadah made a strong impression on me. That is why I once asked Zusha whether I should learn Kabbalah."
    "It happened just before he moved away."
    
    zu "... Whether you should learn Kabbalah?"
    me "Yes."
    "He gave me a smile, but he was looking at me very intensely."
    "Something was different. He seemed very serious."
    "This was the first time I had ever seen him like this."
    zu "I never studied Kabbalah. And I don't intend to."
    me "..."
    me "Oh."

    "That pretty much ended the conversation."
    "I was still afraid of going insane, or worse, so I avoided the Zohar and other books about Kabbalah."
    "I was particularly afraid of Acher's fate."
    "If he, who was a great sage, could be led astray by the Secrets of the Torah, what about me?"
    "I decided then to make Logic my refuge; Tradition, my guide."
    "Not that I couldn't believe in anything beyond Logic."
    "I believed that there was Truth there."
    "But I was afraid to seek it, lest I lose my way. In the realm beyond Logic, there is no road."
    "To study Kabbalah, one must have a sharp eye to recognize the signs indicating the path. Miss one of the markers, and a man could stray to darkness."
    "So instead, I studied the Revealed Wisdom."
    "I learned how to keep kosher, to observe the Shabbos, how to tie tzitzis."
    "I learned about the 613 mitzvos in the Torah, the seven mitzvos from the Rabbis, and the seven mitzvos of the Righteous Gentile, for the children of Noah."
    "Years passed."
    "I grew my Hebrew vocabulary, and studied the Prophets and the Writings."
    "The books of Yehoshuä, Shmuël and Melachim. Amos, Tehilim, Ester and Mishlei."
    "The classic commentaries of Rashi and Radak, the Aramaic translation of Onkelos."
    "But, sometimes..."
    "I saw glimmers of deep secrets."
    "Sometimes, I read about Gematria. Like in the Kitzur Shulchan Aruch, where the author interrupted his legal code to perform numerology with the Hebrew letters of the word \"tzitzis.\""
    "Other times mysteries were in the text of the Torah itself, like Yechezkel's vision of the Chariot."
    "But still..."
    "... to study the Hidden Wisdom in depth, the Secrets of Torah, the Kabbalah..."
    "I waited, yearning, wondering whether I would merit to enter the Orchard of Pardes, to taste of those fruits as well."
    
#########################
    scene black
    show text(bookText(
        "{b}\"He wraps [[Himself with] Light like a garment...\"{/b}\n\nThe Garment is the hinderpart of Wisdom, the revealed aspect of Torah....\n\n[[On the other hand,] the innermost aspect of Wisdom... is the \"Light\" which is clothed in the \"Garment.\" For this is the Light that was created on the First Day, which was \"hidden away for the Tsadikim.\"\n\nAnd where was it hidden away? In the Torah...",
        "Tsemach Tsedek",
        "Yahel Or, on Psalms 104:2"))
    with slowDissolve
    pause
    scene black with dissolve
    show text chapterText(title="The Veil") 
    with dissolve
    pause
    scene black with dissolve
    "Somehow, in a weird way, things began to click as I did more mitzvos."
    "It was very subtle, and I ignored it at first."
    "It didn't make much sense. Mitzvos are actions. Understanding is in the realm of thought."
    "They can't be connected. At the very least, thought leads to action. Not the other way around. Right?"
    "It must be something else."
    "Or is it?"
    me "Come on. Back to Pirkei Avos."
    show text(bookText("He used to say..."))
    with dissolve
    pause
    me "Wait, who's \"he\"?"
    me "It's not in mishna three... Ah. Mishna two."
    show text(bookText("Raban Gamliel, the son of Rabi Yehuda HaNasi says, \"Torah is beautiful with a worldly occupation, for the exertions of the two make sin forgotten...\""))
    with dissolve
    pause
    me "Okay. Back to number four."
    $mishna = bookText("He used to say, \"Make His Will as your will, so that He make your will as His Will.\"", "Mishna, Tractate Avos 2:4")
    show text(mishna)
    with dissolve
    pause
    me "What does {i}that{/i} mean? Isn't that kind of egotistical? \"I'll do what You want, so that You do what I want?\""
    me "On the other hand, if your will is already nullified to God's anyway, is it still egotistical?"
    me "But then, if that's so, and your will at that point is already the same as God's Will..."
    me "... why does it say, \"so that He will make your will as His\"? Aren't they already the same? What's left to do?"
    me "Or are they not the same yet?"
    me "Hanh."
    me "Maybe Bartenura says something..."
    $bartenura = bookText("{b}Make His Will as your will.{/b} Expend your possessions for the Desires of Heaven, by your own will, as if you were expending them for your own desires. For if you do this, He will make your will like His Will. That is to say, He will give you good, generously.")
    show text(bartenura)
    with dissolve
    pause
    me "Gyah. He didn't answer the question."
    me "Or maybe he did."
    me "\"Expend your possessions for... Heaven... as if... for your own desires.\""
    me "Does the ego still exist at that point?"
    me "It's hard to imagine it could."
    show text(mishna)
    with dissolve
    me "But then, the mishna seems redundant. Once the wills are one, there's no need to unify them further."
    me "Unless the unification wasn't complete after the first bit."
    me "Maybe it's a process."
    me "So... maybe it's like this."
    me "Start by changing your will to match His. Then..."
    me "God will take it the rest of the way?"
    me "I kind of like that."
    me "But then, what of Bartenura, who says to completely nullify your own desires first?"
    me "Oh! Maybe that's why he said \"{i}{b}as if{/b}{/i} you were using them for your own desires.\" The desires aren't one yet."
    me "But then, is the self-nullification really complete enough?"
    me "Well, you are going so far as to take concrete action, with your physical possessions - maybe...."
    me "Maybe the next bit explains it?..."
    show text(bookText(
        "{i}Nullify your will before His Will, so that He will nullify the will of others before your will.{/i}",
        "Ibid."))
    pause
    me "Ooof. I need a break."
    hide text with dissolve
    "There is an answer. I know it."
    "I just can't go further, unless I'm willing to vaporize my brain."
    "Closing the book, I lean back in my chair while stretching my neck."
    pn "Benny!"
    me "Ah?"
    "It was from behind me. I crane my neck backwards-"
    me "Pinny!"
    "I stand up and step around the chair, hugging him."
    me "Good to see you!"
    pn "Yeah, and you."
    "It's been months and months since I last saw him. He lives far outside the city."
    me "Let's get an ice cream!"
    pn "Ice cream? Is Yossi around?"
    me "Good point. Let's get him, too."
    pn "Ehhh... Ah. No need."
    ys "{b}Who said ice cream?!{/b}"
    me "Yep, no need."
    ys "Pinny! It's been so long!"
    pn "I know! How've you been?"
    ys "Benny's been taking care of me."
    "Yossi pats his midsection."
    pn "It's smaller than before. You've lost weight since last year, haven't you?"
    me "He burns it off in martial arts."
    pn "Seriously? I gotta watch out!"
    "Yossi put on a bad Japanese accent."
    ys "Karate... CHOP! Hahaha!"
    pn "Scary..."
    me "Ah, so, ice cream, ice cream. Let's go."

    # Scene change
    "At the ice cream parlor..."
    pn "I think... I'll have medium mint chocolate chip."
    me "No sprinkles or anything?"
    pn "Sugar cone. With the star sprinkles over there."
    ys "Mondo Choco! With all the syrups, whipped cream, nuts, granola and a chocolate cup. Large."
    "Pinny gaped at Yossi. His expression was priceless."
    "I laughed, but I had to agree with Pinny..."
    me "I don't understand how you can eat that and still not gain any weight."
    ys "Muscles, you know. It all goes to the muscles."
    pn "No way! Just how many calories are in that thing? That ice cream alone is probably enough to last you a week!"
    me "Ah, just let him have it. Somehow he does it."
    pn "Well, all right, if you say so."
    "Pinny turns to Yossi."
    pn "How often do you eat this anyway?"
    ys "Few times a week."
    pn "WHAT!?"
    pn "Look, you've got such a nice build now! You're gonna inflate like a flabby balloon!"
    ys "Flabby?"
    pn "Flabby."
    ys "FLABBY?!"
    pn "Yeah. -AHH!"
    "Faster than I could blink, Yossi jabbed the sides of his belly. Then, after a moment of target acquisition-"
    pn "EEK!"
    "-he got the button."
    pn "I take it back! I take it back!"
    ys "Hahaha!"
    me "I'll have a medium vanilla with a chocolate sugar cone."
    "Cashier" "Coming right up."
    pn "Yossi, I forgot... how dangerous it was to get between you and ice cream."
    ys "You scream like a girl! Hahaha!"
    pn "Do not!"
    ys "Hahahaha!"
    ys "Hic."


    #s = BookStr("The Almighty saw that the tsadikim were few so He planted them in every generation.",
    #"Gemoro, Yoima 38b")
    
    #show text(bookText(
    #    "He said to her, \"My daughter, why are you sad?\"\nShe said to him, \"I confused the jar of vinegar for the jar of oil, and I lit the lights for Shabbos with it!\"\nSaid he to her, \"Why should it bother you? He who decreed that oil should burn will decree that the vinegar should burn, too.\"\n...It burned and lasted the entire day until they took a flame for havdala from it.",
    #    "Talmud, Tractate Taäinis 25a"))
    return
