label chapter2:
    scene black
    with dissolve
    
    show text chapterText(2, "The Training") with dissolve
    pause
    scene black with dissolve
    show text bookText("The candle of God is the soul of Man, searching the chambers of the depths.", "Proverbs 20:27") with dissolve
    pause
    scene black with dissolve   
    
    "A few years have passed since Pinny and I made rope hammocks in the park trees."
    "We're still friends, but the world around us has... changed... a lot."
    "Zusha's {i}cheder{/i} group was never that large, and when all the kids got older, the community hired another teacher for us, replacing him."
    "So, Zusha moved to Oklahoma City, and we hardly heard from him again. I miss him a lot, and I'm sure Pinny does, too."
    "But that wasn't all."
    "When the recession hit, my dad lost his office job."
    "Without that income, my parents could no longer afford the tuition for a Jewish education."
    "So I went into public school. It was a big shock."
    "To be considered \"in\" over there (which in itself was a concept that I had never seen or heard of before),"
    "... you had to know the latest rap song and be able to break dance."
    "The values just seemed so hollow."
    "I didn't want to become like that."
    "So, on my own, I began to study the Torah."
    "Mostly, it was stuff in English."
    
    "Since Yossi lived nearby, we would see each other fairly often."
    "One of those conversations went something like this."
    me "Hi Yossi!"
    ys "Benny!"
    me "How do you become a tsadik?"
    "A pause."
    ys "Hic?"
    "Uh-oh. I got his hiccups started."
    ys "Ahhh-hic-hic."
    me "Oh, no."
    ys "Don't wo- *hic* worry about it. Hic."
    me "Breathe slowly."
    ys "Hic."
    "An ice cream later, he was back to normal."
    ys "Hah-h-h. Thanks, Benny."
    me "No problem!"
    me "{i}Boruch atoh adoinoi, eloheinu melech haölom, boirei nefashos rabos v'chesroinon al kol mo sheboroso lehachayois bohem nefesh kol chai.{/i}"
    ys "What're you saying?"
    me "{i}Boruch chei haölomim.{/i} -For the ice cream pop."
    ys "You say a brocho after ice cream?"
    me "Yeah. I just noticed it in the bentsher yesterday, after the \"Grace After Meals.\""
    ys "You mean, \"bentshing\"?"
    me "Yeah."
    ys "That sounds so Shakespeare!"
    me "Yeah, doesn't it?"
    ys "It's like \"Tabernacle\" for \"Mishkan\" and, em, what do they call the menorah?"
    me "Candelabrum. Isn't that so over-the-top?"
    ys "I know! Why can't they just use {i}normal English?{/i}"
    "We both laugh, but I stop quickly."
    me "Hey, don't get the hiccups again, unless you want to get the ice cream this time!"
    ys "Hahaha! Hic!"
    me "{b}NO-O-O!{/b} Not the hiccups again!"
    ys "Haha-*hic*-haha-*hic*!"
    "Yossi was a good sport and bought the next round of ice creams."
    me "So what do you think about the question from before?"
    ys "Hmmm. Oh, the tzadik thing?"
    me "Yeah."
    ys "I guess you gotta be a Talmud chochem."
    "A chochem is a scholar."
    me "So, I've gotta study Talmud?"
    ys "Yeah."
    me "Hmmm."
    me "Oh! It's lunchtime!"
    "Yossi's mom was mostly strict about one thing, and that was mealtimes."
    ys "You're right! Gotta go!"
    me "See you later, Yossi!"
    ys "Bye!"
    "That afternoon, I took the one volume of Talmud my dad had, and tried to read it in Aramaic."
    "It had the vowels added in, so the sounding out the words wasn't too hard."
    "It's just that I had absolutely no idea what I was reading at all."
    "So I read for a while."
    "Then my eyelids began to droop."
    "And then I fell asleep on the couch."
    "I guess that I bit off more than I could chew."
    "From then on, I stuck with the English."
    "When I got older, I put a finger in the Hebrew and the English at the same time. Matching up the words helped me learn the language."
    "It was slow going, but I made some progress."
    "When I was twelve, I could understand about half of the siddur, or the Jewish prayerbook."
    "At thirteen, I knew about 75%, and I could understand about half of the Chumash, the Five Books of Moses."
    "It helped a lot that the vocabulary of the Holy Tongue was very simple, with few extra frills, or so I thought."
    "Later books of the Writings and the Prophets were much more flowery and poetic, and I couldn't even tell what the topic was most of the time."
    "Still though, I stuck with it."
    "Maybe it was because I found Pirkei Avos in the siddur one day after davening."
    "It was a huge collection of Jewish aphorisms - it really got into human psychology, self-improvement and stuff like that."
    "Or maybe it was because I kept asking questions from the rabbi and kept getting answers."
    "I started feeling that no matter what the question, there was always an answer."
    "Maybe it was just that there were entire fields of Jewish knowledge that I had no idea about, like Talmud and Kabbalah."
    "The possibilities and knowledge just waiting out there made me want to go out and get it for myself."
    "But at the same time as I was exhilarated by the knowledge, I was also in awe and a bit of fear of it."
    "There is a story about this in the Talmud."
    #Scene change here to indicate the beginning of a story
    "There are four levels of understanding Torah, four different realms."
    "There is P'shat, Remez, Drush and Sod."
    "P'shat is the plain meaning of the verse."
    "Remez is allusion, and links the verses in different places together."
    "Drush is more esoteric, explaining the finer hinting of the words in the Torah. Often, this contains the stories in between the lines of the Torah."
    "Sod is the deepest and most esoteric aspect of the Torah. Few people are privileged to learn it."
    "Sod means \"secret.\""
    "It covers the mystical aspects of Torah."
    "Together, these four layers of understanding are abbreviated as PaRDeS."
    "\"There were four men that entered Pardes.\""
    "\"They were Ben Azai, Ben Zoma, Acher, and Rabbi Akiva.\""
    "\"He said to them:\""
    "\'When you reach stones possessing purity, do not say, \"Water, water!\"\'"
    "\'For it is said, \"One who speaks falsehood will not be guiltless in My eyes.\"\'"
    "\"Ben Azai peered in and died.\""
    "\"Scripture says of him, \'Precious in the eyes of God is the death of His pious.\'\""
    "\"Ben Zoma peered in and became insane.\""
    "\'Scripture says of him, \"Have you found honey? Eat what is enough for you, so that you not be filled with it and vomit it.\'\""
    "\"Acher cut down the plantings.\""
    "\"Rabbi Akiva came out in peace.\""
    #Scene change back to normal
    "This is why I once asked Zusha whether I should learn Kabbalah."


    "Once, before Zusha had left, I asked him about Kabbalah."

    # $ BookQuote("Why should it bother you? He who decreed that oil should burn will decree that the vinegar should burn, too.",
    # "Gemoro, Ta'ainis 25a")
    #s = BookStr("The Almighty saw that the tsadikim were few so He planted them in every generation.",
    #"Gemoro, Yoima 38b")
    
    return
