label chapter2:
    scene black
    with slowDissolve
    
    show text chapterText(2, "The Training") with dissolve
    pause
    scene black with dissolve
    show text bookText("The candle of God is the soul of Man, searching the chambers of the depths.", "Proverbs 20:27") with dissolve
    pause
    scene black with dissolve   
    
    "A few years have passed since Pinny and I made rope hammocks in the park trees."
    "We're still friends, but the world around us has... changed... a lot."
    "Zusha's {i}cheder{/i} group was never that large, and when all the kids got older, the community hired another teacher for us, replacing him."
    "So, Zusha moved to Oklahoma City, and we hardly heard from him again. I miss him a lot, and I'm sure Pinny does, too."
    "But that wasn't all."
    "When the recession hit, my dad lost his office job."
    "Without that income, my parents could no longer afford the tuition for a Jewish education."
    "So, when I was ten, I went into public school. It was a big shock."
    "Everyone was talking about what was \"in.\""
    "Being \"in\" was a concept that I had never seen or heard of before."
    "It seemed that to be \"in,\" you had to know the latest rap song and be able to break dance and play sports."
    "The values just seemed so hollow."
    "I didn't want to become like that."

    inner  "So, nu?"
    inner "What do you want to be?"
    "What I was, what I wanted to be... it bothered me at night, too."
    "Why couldn't things be simple, like they were before?"
    
    zu_mem "Your mission, though. Hmmm-hm."
    zu_mem "Well, what would {i}you{/i} like to do?"
    me_mem "I wanna be {i}tsadik{/i} just like little Yisroël!"

    "Oh, how much has changed since then!"
    "The loneliness, the darkness around me now didn't exist back then."
    "Now, it seems to cast a shadow over everything."
    "Even physically, the grass and the sky don't seem to shine as brightly as in my memories."
    inner "Do you still even want to be a tsadik?"
    me "..."
    me "Yes... I think."
    me "Well, {i}want to{/i} want to be one..."
    me "But..."
    me "I don't know."
    me "I guess..."
    inner "...Other things have pushed it aside."
    me "Well, yes. I guess they have."
    me "The delight in building gadgets in the workshop downstairs. Making music. Writing."
    inner "You can't choose all of them, you know. Only one."
    inner "Only if you focus your efforts can you actually {i}do...{/i}"
    me "...do what?"
    inner "Well, what do {i}you{/i} want to do?"
    me "..."
    me "...I do like helping others."
    me "A little spark of that old desire is still there."
    me "To be a tsadik."
    "I look more closely at it."
    inner "A worthy choice."
    inner "But you are still full of doubt."
    inner "You genuinely like the other things too, don't you?"
    me "...Yes, I do."
    inner "Like music."
    me "Yes, but..."
    me "...if I pursue these other interests, could my work actually have a real impact?"
    me "Music may inpire for a moment, but once the music passes, the inspiration is gone."
    me "Music alone can't change a person's whole life, let alone the whole world."
    me "Not unless he marries her and she becomes literally his bread and water."
    me "Even then, does he become a better person?"
    inner "Okay, so you won't devote your life to music. I can understand that."
    inner "What about making gadgets?"
    inner "That will definitely have an impact. Just look at the past decade!"
    "He's right."
    "Web 2.0. The iPhone. Smartcards. Video chat. Facebook."
    "But..."
    "...the answer has no soul."
    me "Well, yes, you are right that technology can change our lives."
    me "It can even change the world. It has."
    me "But its power and flexibility is also its weakness."
    me "Technology is just another kind of power. A body with no soul."
    me "Just like money, energy, intelligence."
    me "It is inherently neither good nor evil."
    me "It all depends on the one who wields it."
    me "There is no way I can make sure it is used for good."
    me "Besides, even if I develop a device that could stop all war, how long would that last before another technology makes it obsolete?"
    me "Technology is constantly changing."
    me "My invention could even be used in a weapon!"
    me "After all, destroying is easier than building."
    me "I've seen that in my workshop downstairs."
    inner "Touché."
    "I pause and think some more."
    "What else could I do?"
    inner "Well, if you are worried about making sure it helps and does good, what about writing?"
    inner "Writing can be inspire people. It could even be useful."
    me "True, true."
    me "But that's only as long as they remember what I write about."
    me "If I write nonfiction on something, the only people who will constantly remember it are those that study that one field."
    me "Aside from that, how often do you see nonfiction changing someone's life?"
    me "I want to inspire people. I want to change the world."
    "I chuckle to myself."
    me "Well, first I have to inspire myself."
    me "Unless it inspires me, I can't really inspire others with it, can I?"
    me "Nonfiction won't cut it."
    inner "What about fiction, then? That's inspiring."
    me "Yeah, that's true."
    me "But ultimately, no fictional universe can ever really exist."
    inner "What do you mean? Don't these universes exist in people's hearts?"
    inner "Like Tolkien's Lord of the Rings."
    inner "Everyone says that it's a masterpiece. Tolkien devoted nearly his entire life to it."
    inner "Don't tell me that fiction's not inspiring."
    "At first, I can't answer. He has a point, but something is wrong."
    me "...Well, I've got to agree. It's inspiring."
    me "Heck, I am overawed by the sheer depth, quality, detail and passion of the series."
    me "Noble warriors, tales of courage, legends of eternal love."
    me "Truly, an epic story. Magnificent. Inspirational." 
    "Then it hit me. What was wrong with it."
    me "But do people really live differently because of it? Did it really change the world?"
    me "Aside from the film padding some wallets and depleting some others, did Tolkien have a tangible effect on the world?"
    me "I really want to say it did."
    me "An effort like that, a passion like that deserves it."
    me "But I can't see it."
    me "..."
    me "I think the tale was so magical and legendary that it remained trapped in Middle-Earth."
    inner "Tricky, tricky, isn't it?"
    inner "It's got to inspire you {i}and{/i} inspire other people."
    inner "And not only that, it's got to change world in a down-to-earth way."
    me "So..."
    me "...A tsadik."
    inner "Hahahaha!"
    inner "You say that so easily."
    inner "You think that {i}you{/i} can be a tsadik?"
    me "I..."
    
    me "I don't know."
    inner "Exactly. Back to square one."
    inner "You still have doubts."
    inner "Do you want to devote everything to this?"
    inner "Is it even possible for you to achieve this?"
    inner "Isn't it too much to expect perfection from yourself?"
    inner "Can {i}anyone{/i} achieve this?"
    me "But they can! They have!"
    me "Zusha told me!"
    me "There's the Baal Shem Tov, the Maharal of Prague, Rabbi Akiva, Hillel, Moshe Rabeinu!"
    me "They all existed! they did it!"

    inner "Yes, but that's them."
    inner "What are you?"
    inner "They lived in an age of miracles."
    inner "Not you."
    inner "They were towers of morality and faith! Their time was different from ours."
    inner "But you... you are just a puny speck of dust next to them."
    me "This is... too cruel..."
    inner "Look at this darkness around you!"
    inner "How do you think you can overcome this?"
    "Please..."
    inner "You are already overcome!"
    inner "Look at yourself honestly now. Can you say that you are on their level?"
    "My eyelids tremble as my tears flow."
    "I know that I am nothing next to the spiritual giants of old."
    "But why does this bother me so much?"
    "Did I really expect myself to be perfect?"
    inner "Do you think that you are so holy?"
    me "No..."
    "My inner voice took on a more cynical air."
    inner "How many, how many?"
    inner "Just how many sins do you think have sullied your soul?"
    inner "A hundred? A thousand? Ten thousand?"
    me "NO!"
    inner "These sins here are only the ones you know about."
    inner "But God misses nothing."
    inner "He can count the ones you {i}don't{/i} know about, too!"
    me "Oy... Oy...."
    inner "Hopeless, no? Another here, another there..."
    me "AAAGH!!!"
    inner "And you want to be a tsadik?"
    inner "Ha!"
    inner "Ha! Ha! Hahahahaha!"
    me "NO!"
    "My darkened bedroom vibrates momentarily from my outburst."
    "Frightened a bit, I sit up in bed, hugging my knees. I think I woke my parents."
    "I hear footsteps down the hall."
    "Bare feet pad gently on the thin carpet. The floorboards creak slightly as the steps come closer."
    "It's my mom."
    mom "Benny?"
    "She switches on my desk lamp. It's not as bright as the overhead light, but it's enough to see my mom's worried face."
    mom "You were screaming."
    "I nod slightly."
    "She comes and sits on my bed, beside me."
    mom "Was it a nightmare?"
    me "..."
    me "Yeah."
    "I'm still shaking under the covers. I feel cold. My pajama top is sticky with sweat."
    mom "Do you want some water?"
    me "Yes, please."
    mom "Okay, Benny. I'll be right back."
    "A tinkle of glass tumblers. A faucet runs in the kitchen."
    "I notice how the pitch of the rushing water rises before it shuts off."
    "Soon, she comes back in my room with the water. Pushing away the sheets, I sit up and gratefully take it."
    me "Thanks, Mommy."
    "She smiles and sits next to me on the bed. She feels warm, reassuring."
    me "{i}Boruch atoh adoinoi, eloiheinu melech haöilom, shehakoil nihiyoh b'dvaroi.{/i}"
    mom "Amein."
    "The water feels good on my dry throat. I put it down after a few gulps."
    "After sitting together like this for a while, my mom shifts a little."
    mom "Do you want to tell me about your nightmare?"
    "I pause a moment."
    me "It was about what I want to be when I grow up."
    "She nods."
    me "I don't really know. I think..."
    me "I think I want to be a tsadik."
    me "But I don't know if I can."
    me "It seems so hard to give up on everything else. The gadgets. The music."
    
    mom "Benny."
    mom "No matter what you become, I will always love you."
    mom "But please, Benny, don't give up on anything."
    mom "All the things you can do, God has given you as a gift."
    mom "Becoming a tsadik doesn't mean that you have to throw it all away."
    mom "The Rebbe said that we've got to use all of our skills, all of our power to bring Moshiach now."
    mom "A tsadik doesn't throw any of his talents away. He uses them to serve God."
    mom "Did you know that the Rebbe was an engineer?"
    me "No."
    mom "He did work for the US Navy before he became Rebbe."
    mom "Even after he became Rebbe, he would help other scientists with their work."
    me "I didn't know that."
    mom "Benny, you are special. God gave you special abilities."
    mom "Don't throw them away. Find a way to use them for good."
    "I nod."
    "We sit together a bit longer, and I drink some more water."
    mom "Do you think you can sleep now?"
    me "Yeah, I think so."
    mom "I'll turn off the light, then."
    "She gets up and switches the lamp off again."
    mom "Good night, Benny. I love you!"
    me "Good night, Mommy."
    "She closes the door."
    me "I love you, too."

    "Her footsteps fade away in the renewed darkness, but I still feel her warmth."
    "I hug my knees to keep the warmth as long as I can."
    "After waiting a bit, I hear nothing."
    "Nothing but the crickets outside, and the fridge motor running, far off in the kitchen."
    "That, and the tiny, high-pitched noise of blood rushing in my ears."
    "That little noise never stops. It's never completely silent."
    "Just like my inner voice."
    "Always questioning."
    inner "Do you really want to be a tsadik?"
    "Doubting."
    inner "What do you want to be?"
    "Repeating."
    "I try to figure out what to do about it."
    "Should I ignore it?"
    "It might die down eventually."
    "If I manage to outlast it."
    inner "What do you want to be?"
    "But is the question it asks really bad?"
    inner "What do you want to be?"
    "Wait. Is that really what it's asking?"
    "I already answered the question. I want to be a tsadik!"
    "What is that inner voice really asking?"
    "It has a problem with the answer I'm giving?"
    inner "Exactly."
    inner "You answered in words. Did you answer with your core?"
    me "My core?"
    inner "I still heard doubt. Fear."
    me "Fear..."
    me "Yes, there is a fear there."
    me "A fear that I could fail."
    me "That I could be overcome."
    me "That I might never become a tsadik."
    me "A fear that I am hoping for too much."
    inner "You answered with words. Words are external."
    inner "Promises, promises. What will {i}actually{/i} happen?"
    me "What will {i}actually{/i} happen?"
    inner "Words can lie."
    shout "{i}But not your core.{/i}"
    inner "Look into your core. Your inner self. What do you want?"
    inner "What do you see?"
    me "Where {i}is{/i} my core?"
    inner "Until your inner self is sure, your future will contain fear and doubt."
    "I rest my head against my knees and whisper into the darkness."
    me "God... God... Where is my core?"
    "The outside world fades from my consciousness, leaving only me."
    "My body dissolves away just like it."
    me "God... Where is my core?"
    "My mind floats through the darkness."
    "I see random colors speckling my vision. An orange web, with rough, angular shapes of green."
    me "Please, God... where?"
    me "Where am {i}I?{/i}"
    me "What am I?"
    "My perception of time broadens."
    me "What was/will be me?"
    "The darkness deepens. I see something."
    "It has no recognizable form. It's just floating in nothingness. Dark. So dark!"
    "But there is a little light coming from it."
    "A tiny light."
    "Motionless."
    "I will it to change, but nothing happens."
    inner "You must decide with your core."
    "I strengthen my focus on it."
    "Still, nothing."
    inner "Decide... with your inner self."
    "Speckles fill my vision as I lose concentration."
    "A distant train horn sounds, and I hear the boxcars rattling over the tracks."
    "I open my eyes. I don't feel so tired."
    "I just feel lost. Something didn't click."
    "The alarm clock beside me glows 11:34 in red digits."
    "Despite my alertness, I get back under the covers and close my eyes."
    "I open then again. 11:34."
    "I close them for a while."
    "Then I open them. 11:37."
    "I shut them again."
    "11:40."
    "11:45."
    inner "Until your inner self is sure..."
    inner "...your future...."
    "The rest of the message is lost."
    "Except..."
    inner "What do you want to be?"
    "11:54."
    "I close my eyes again and focus on relaxing, not moving my body."
    "Sleep envelops me...."

    "The next day, the questions still echo in my mind."
    me "Do I even know what a tsadik is?"
    me "I know what a tsadik does."
    me "But, if words are external, what about actions?"
    me "Compared to speech, aren't actions more external? Separated from the core?"
    me "But then, aren't they also an expression of the internal?"
    me "Aren't actions things that a person felt so necessary that he brought it from potential to actual?"
    me "What is the connection between speech and action?"
    "My thoughts wander through the labyrinth."
    me "A tsadik doesn't lie."
    me "In a tsadik, his inside and outside match."
    me "His words and actions match his thoughts."
    inner "Yes. But..."
    inner "...it's much, much deeper than that."
    inner "Everything - his thoughts, speech and action - everything is aligned with his inner self."
    inner "A tsadik's inner self is sure. Firm."
    inner "Since his externality flows from that, so does his future."
    inner "Everything comes because of his pure inner core."
    me "I guess that's the soul."
    me "But what about my question?"
    me "How do I become like that?"
    shout "{i}How do I strengthen my inner self?{/i}"
    me "How do I strengthen my soul?"
    me "How do I give it direction?"
    "... And so the day wore on. The questions cycled in my mind."
    "They were still circling in my mind when I met Yossi."
    "Since Yossi lives nearby, we would see each other fairly often."
    scene bg forestPavedPath1 with dissolve
    me "Hmm? Oh! Hi Yossi!"
    ys "Benny!"
    inner "Does strengthening the soul change what it is?"
    inner "Or does it just amplify what was there before?"
    me "I have no idea..."
    ys "Oi, Benny."
    me "Huh?"
    ys "You've got that look again. What's up?"
    
    "I look at him."
    me "How do you become a tsadik?"
    ys "..."
    ys "*Hic?*"
    "Uh-oh. I got his hiccups started."
    ys "Ahhh-*hic*-*hic.*"
    me "Oh, no. Your hiccups-"
    ys "Don't wo- *hic* worry about it. *Hic.*"
    me "Breathe slowly."
    ys "*Hic.*"
    ys "Do you *hic* have something *hic* to eat?"
    "... An ice cream later, he was back to normal."
    ys "Hah-h-h. Thanks, Benny."
    me "No problem!"
    "Of course, I didn't mind eating some, too."
    me "{i}Boruch atoh adoinoi, eloiheinu melech haöilom, boirei nefashos rabois v'chesroinon al kol mo sheboroso lehachayois bohem nefesh kol chai.{/i}"
    ys "What're you saying?"
    me "{i}Boruch chei haölomim.{/i} -For the ice cream pop."
    ys "You say a brocho after ice cream?"
    me "Yeah. I just noticed it in the bentsher yesterday, after the \"Grace After Meals.\""
    "A look of comprehension slowly dawns on him."
    ys "You mean, bentshing?"
    me "Yeah."
    ys "That sounds so Shakespeare!"
    me "Yeah, doesn't it?"
    ys "It's like \"Tabernacle\" for \"Mishkan\" and- em, what do they call the menorah?"
    me "Candelabrum. Isn't that so over-the-top?"
    ys "I know! Why can't they just use {i}normal English? \"Candelabrum\"-{/i} Oy vey!"
    "We both laugh, but I stop quickly."
    me "Hey, don't get the hiccups again, unless {i}you{/i} want to get the ice cream this time!"
    ys "Hahaha! *Hic!*"
    me "{b}NO-O-O!{/b} Not the hiccups again!"
    ys "Haha-*hic*-haha-*hic!*"
    "Yossi was a good sport and bought the next round of ice creams."
    me "So what do you think about the question from before?"
    ys "Hmmm. Oh, the tsadik thing?"
    me "Yeah."
    ys "I guess..."
    "He's speaking slowly, brow furrowed in thought."
    ys "... you've gotta be a Talmud chochem."
    "A chochem is a scholar."
    me "Talmud?"
    ys "Yeah. All those tsadikim in Zusha's stories were chochomim."
    ys "Maybe that's it."
    me "Hmmm."
    me "Oh! It's lunchtime!"
    "Yossi's mom was mostly strict about one thing, and that was mealtimes."
    ys "You're right! Gotta go!"
    me "See you later, Yossi!"
    ys "Bye!"
    "I felt kind of sorry for him."
    me "Two ice creams, then lunch..."
    "I cringe."
    me "Oo-oohhh. Poor guy!"
    me "Wait a minute... what about me?"
    me "Ohhhh no. Oy vey."
    me "Oy vey, oy vey."
    
    scene black with mediumDissolve
    "... That afternoon (after a {i}quick{/i} lunch), I took the one volume of Talmud my dad had, and tried to read it in Aramaic."
    "It had the vowels added in, so sounding out the words wasn't too hard."
    me "{i}Sha... mm... mai? Om...er? Kol. Han...nashim?...{/i}"
    "It's just that I had absolutely no idea what I was reading at all."
    "But I kept reading."
    "For a while."
    "Then my eyelids began to droop."
    "And then I fell asleep on the couch."
    "I guess that I bit off more than I could chew."

    "Still, even though I didn't really get anything from that Talmud session on the couch..."
    "I'm glad I talked to Yossi."
    "He might not have answered my question."
    "But, I realized eventually that he introduced a new question, which I had a chance of answering."
    shout "Where can I find the answers?"
    "In other words, I wasn't alone. Others have come before me, seeking the same path."
    "People who have already done this would know."
    "Chochomim. Tzadikim."
    "They would have the answers."
    "I've got to see what {i}they{/i} say."


    scene bg forestPathUp1 with dissolve
    "Spurred by this thought, I continued learning Torah on my own."
    "Especially the Oral Traditions committed to writing by the chochomim and tsadikim of old."
    "At first, it was mostly stuff already translated into English."
    "I knew that it was filtered down a little bit, because the titles and authors clearly indicated their original language."
    "Pirkei Avos. Chovos Halevavos. Rambam. Rabi Yochanan ben Zakkai. Hillel."
    "While I did learn a fair deal, the English commentaries showed that there were thousands of nuances that could only be seen in the original language."
    "I longed to see all the nuances, as they were in the original."
    "When I got older, I would put one finger in the Hebrew and one finger in the English at the same time. Matching up the words helped me learn the language."
    "It was slow going, but I made some progress."
    "When I was twelve, I could understand about half of the siddur, or the Jewish prayerbook."
    "At thirteen, I knew about 75\%, and I could understand about half of the Chumash, the Five Books of Moses."
    "It helped a lot that the vocabulary of the Holy Tongue was very simple, with few extra frills."
    "Or so I thought."
    "Later books of the Writings and the Prophets were much more flowery and poetic, and I couldn't even tell what the topic was most of the time."
    "Still though, I stuck with it."
    "Maybe it was because I found Pirkei Avos in the siddur one day after davening."
    "It was a huge collection of Jewish aphorisms - it really got into human psychology, self-improvement and stuff like that."
    "Or maybe it was because I kept asking questions from the rabbi and kept getting answers."
    "I started feeling that no matter what the question, there was always an answer."
    "Even if the initial answer was \"I don't know,\" I usually found the answer somewhere, sometime later on."
    "Maybe it was just that there were entire fields of Jewish knowledge that I had no idea about, like Talmud and Kabbalah."
    "The possibilities and knowledge just waiting out there made me want to go out and get it for myself."
    "But at the same time as I was exhilarated by the knowledge, I was also in awe and a bit of fear of it."
    "There is a story about this in the Talmud."
    scene black with mediumDissolve
    #Scene change here to indicate the beginning of a story
    "There are four levels of understanding Torah; four different realms."
    "There is P'shat, Remez, Drush and Sod. All of them can be true at the same time."
    "P'shat is the plain meaning of the verse."
    "Remez is allusion, which links the verses in different places together."
    "Drush is more esoteric, explaining the finer hinting of the words in the Torah. Often, this contains the stories in between the lines of the Torah."
    "Sod is the deepest and most esoteric aspect of the Torah. Few people are privileged to learn it."
    "Sod means \"secret.\""
    "It covers the mystical aspects of Torah."
    "Together, these four layers of understanding are abbreviated as PaRDeS."
    "Says the Talmud:"
    "\"There were four men that entered Pardes.\""
    "\"They were Ben Azai, Ben Zoma, Acher, and Rabbi Akiva.\""
    "\"He said to them:\""
    "\'When you reach the pure marble stones, do not say, \"Water, water!\"\'"
    "\'For it is said, \"One who speaks falsehood will not be guiltless in My eyes.\"\'"
    "\"Ben Azai peered in and died.\""
    "\"Scripture says of him, \'Precious in the eyes of God is the death of His pious.\'\""
    "\"Ben Zoma peered in and became insane.\""
    "\'Scripture says of him, \"Have you found honey? Eat what is enough for you, so that you not be filled with it and vomit it.\'\""
    "\"Acher cut down the plantings, [going astray in heresy].\""
    "\"Rabbi Akiva came out in peace.\""
    #Scene change back to normal
    "This is why I once asked Zusha whether I should learn Kabbalah."
    "It happened before he had left."
    
    zu "Whether you should learn Kabbalah?"
    me "Yes."
    "He gave me a smile, but he was looking at me very intensely."
    "This was the first time I had ever seen him like this."
    zu "I never studied Kabbalah. And I don't intend to."
    me "... Oh."

    "That pretty much ended the conversation."
    "I was still afraid of going insane, or worse, so I avoided the Zohar and other books about Kabbalah."
    "I was particularly afraid of Acher's fate."
    "If he, who was a great sage, could be led astray by the Secrets of the Torah, what about me?"
    "My refuge was in Logic; my guide, Tradition."
    "Not that I couldn't believe in anything beyond Logic."
    "I believed that there was Truth there."
    "But I was afraid to seek it, lest I lose my way in the realm beyond Logic."
    "So, I studied the Revealed Wisdom."
    "On the other hand, for the Hidden Wisdom, the Secrets of Torah, the Kabbalah -"
    "I waited, yearning, wondering whether I would merit to taste of those fruits as well."
    

    # $ BookQuote("Why should it bother you? He who decreed that oil should burn will decree that the vinegar should burn, too.",
    # "Gemoro, Ta'ainis 25a")
    #s = BookStr("The Almighty saw that the tsadikim were few so He planted them in every generation.",
    #"Gemoro, Yoima 38b")
    
    return
